#!/usr/bin/env python3
import requests
import uuid
import zstd
from datetime import datetime

id = uuid.uuid4()

print(f"[{datetime.now()}] UUID: {id}")
with open("uuid", "w") as file:
    file.write(id.hex)
with open("source/token", "r") as file:
    token = file.read().rstrip()
with open("/autograder/submission_metadata.json", "rb") as file:
    metadata = zstd.ZSTD_compress(file.read())
start = f"https://duckduckwhale.ucsd.edu/api/v1/<course>/<hw>/run/{id}/start"
headers = {
    "Authorization": "Bearer " + token,
    "Content-Type": "application/json",
    "Content-Encoding": "zstd"
}
response = requests.post(start, headers=headers, data=metadata)
if not response.ok:
    print(f"[{datetime.now()}] Error: failed to send start request to observability backend")
    print(f"[{datetime.now()}] Code: {response.status_code}")
    print(f"[{datetime.now()}] Content: {response.content.decode('utf-8')}")
